account = [
    "всего инвесторов"
    "инвесторов",
    "пользователей",
    "зарегистрировано",
    "участники проекта",
    "всего участников",
    "участников",
    "участники",
    "регистрации",
    "инвесторы",
    "игроков",
    "чел",
    "total account",
    "total accounts",
    "total clients",
    "total members",
    "total investor",
    "total investors",
    "registered accounts",
    "total registered",
    "total users",
    "total players",
    "total member",
    "global customer",
    "active accounts",
    "active partners",
    "total user",
    "participants",
    "investors",
    "customers",
    "members",
    "clients",
    "users",
    "partners",
]


investment = [
    "Пополнено (все сезоны)",
    "в казне денег",
    "всего пополнено",
    "инвестированно",
    "всего депозитов",
    "всего инвестировано",
    "сумма инвестиций",
    "сумма пополнений",
    "привлеченные инвестиции",
    "всего пополнений",
    "инвестировано",
    "пополненно рублей",
    "объем инвестиций",
    "депозиты",
    "депозитов",
    "пополнено",
    "пополнений",
    "резерв проекта",
    "резерв",
    "total accepted funds",
    "total investment",
    "total invested",
    "total deposited",
    "total deposits",
    "total deposit",
    "platform turnover",
    "total accepted",
    "deposited",
    "invested",
    "deposits",
    "funds",
]

withdrawal = [
    "всего выплачено",
    "выведено руб",
    "выплачено (все сезоны)",
    "заработано участниками",
    "выплачено всего",
    "выведено",
    "заработано",
    "выплачено",
    "выплат",
    "выплаты",
    "total payments",
    "total withdraw",
    "total withdrawn",
    "total withdrawal",
    "total withdrawals",
    "payments to investors",
    "total payed",
    "total payouts",
    "total paid",
    "paid out",
    "payout",
    "withdrawn",
    "earned",
    "paid",
]