version: '3.7'
services:
  redis:
    image: "redis:alpine"
    restart: always
    env_file:
      - ./celery/.env
    command: 'redis-server --requirepass ${REDIS_PASSWORD}'
    ports:
      - '6380:6379'
      
  worker:
    build: 
      context: ./worker
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ./worker/.env
    command: 'celery -A celeryapp.celery worker -Q diff -E -l info'

  worker-beat:
    build:
      context: ./worker
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ./worker/.env
    command: 'celery -A celeryapp.celery beat -l=INFO'

  hub:
    image: selenium/hub
    restart: always
    ports:
      - 4445:4444

  chrome:
    image: selenium/node-chrome-debug
    restart: always
    ports:
      - 5556:5900
    environment:
      HUB_HOST: hub
      HUB_PORT: 4444
    depends_on: 
      - hub
    entrypoint: bash -c 'SE_OPTS="-host $$HOSTNAME" /opt/bin/entry_point.sh'

  flower:
    build: 
      context: ./worker
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ./worker/.env
    command: 'celery flower -A celeryapp.celery --address=0.0.0.0 --port=5656'
    ports:
      - 5657:5656